networks:
  nginx-proxy-manager:
    external: true

services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    networks:
      - nginx-proxy-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - WATCHTOWER_NOTIFICATION_URL=discord://${DISCORD_WEBHOOK_TOKEN}@${DISCORD_WEBHOOK_ID}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE='0 0 4 * * *'
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - TZ=Europe/Madrid
    restart: unless-stopped
    labels:
      glance.name: Watchtower
      glance.icon: si:watchtower
      glance.description: Docker Container Updater
      glance.category: services
      glance.hide: false
      glance.id: watchtower
