services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:5
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=${TZ:-Etc/UTC}
    labels:
      glance.name: UpSnap
      glance.description: Wake on LAN
      glance.url: https://upsnap.pi.gerardgascon.com
      glance.category: services
      glance.hide: false
      glance.id: upsnap
