services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    env_file:
      - .env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_ROUTES=192.168.50.0/24
    volumes:
      - ./config:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    devices:
      - /dev/net/tun
    hostname: docker-exit-node
    network_mode: host
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    labels:
      glance.name: Tailscale
      glance.icon: si:tailscale
      glance.description: Zero Trust Access
      glance.category: services
      glance.hide: false
      glance.id: tailscale
