services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    labels:
      glance.name: Uptime Kuma
      glance.icon: si:uptimekuma
      glance.url: https://uptime.pi.gerardgascon.com
      glance.description: Service Monitoring Tool
      glance.category: services
      glance.hide: false
      glance.id: uptime-kuma

networks:
  default:
    external: true
    name: nginx-proxy-manager