server:
  proxied: true

pages:
  - name: Sakamoto's Startpage
    center-vertically: true
    hide-desktop-navigation: true
    show-mobile-header: false
    columns:
      - size: full
        widgets:
          - type: search
            search-engine: duckduckgo

          - type: docker-containers
            title: Services
            hide-by-default: true
            running-only: false
            category: services
      
      - size: small
        widgets:
          - type: bookmarks
            title: Servers
            groups:
              - links:
                - title: Kamaji
                  url: https://kamaji.gerardgascon.com/
                - title: Sakamoto
                  url: https://sakamoto.gerardgascon.com/

          - type: dns-stats
            cache: 5s
            service: pihole-v6
            url: https://pihole.sakamoto.gerardgascon.com
            password: ${PIHOLE_PASSWORD}