server:
  proxied: true

branding:
  hide-footer: true

pages:
  - name: Startpage
    width: slim
    center-vertically: true
    hide-desktop-navigation: true
    show-mobile-header: false
    columns:
      - size: full
        widgets:
          - type: search
            search-engine: duckduckgo
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}

          - type: docker-containers
            title: Services
            hide-by-default: true
            running-only: false
            category: services