services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    labels:
      glance.name: Nginx Proxy Manager
      glance.description: Reverse Proxy
      glance.url: https://nginx.sakamoto.gerardgascon.com
      glance.icon: si:nginxproxymanager
      glance.category: services
      glance.hide: false

networks:
  default:
    external: true
    name: nginx-proxy-manager